application/models.py
# Import models from all of our modules
from .users.models import *

# TODO: import any custom models here

application/users/models.py
from application.core import db
from flask.ext.security import UserMixin, RoleMixin

import json

# Define User and Role models (that Flask-Security expects)
roles_users = db.Table('roles_users',
        db.Column('user_id', db.Integer(), db.ForeignKey('users.id')),
        db.Column('role_id', db.Integer(), db.ForeignKey('roles.id')))

class Role(db.Model, RoleMixin):
    ''' Role based security via Flask-Security '''
    __tablename__ = "roles"

    id = db.Column(db.Integer(), primary_key=True)
    name = db.Column(db.String(80), unique=True)
    description = db.Column(db.String(255))

class User(db.Model, UserMixin):
    ''' User Model from Flask-Security '''
    __tablename__ = "users"

    # Base Flask-Security columns
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(255), unique=True)
    password = db.Column(db.String(255))
    active = db.Column(db.Boolean())
    roles = db.relationship('Role', secondary=roles_users, backref=db.backref('users', lazy='dynamic'))

    # Flask-Security column for confirming users (SECURITY_CONFIRMABLE)
    confirmed_at = db.Column(db.DateTime())

    # Flask-Security column for tracking users (SECURITY_TRACKABLE)
    last_login_at = db.Column(db.DateTime())
    current_login_at = db.Column(db.DateTime())
    last_login_ip = db.Column(db.String(length=40))
    current_login_ip = db.Column(db.String(length=40))
    login_count = db.Column(db.Integer())

    # Custom Data
    first_name = db.Column(db.String(length=40))
    last_name = db.Column(db.String(length=40))

    # Flask-Social column (found from flask-social-example)
    connections = db.relationship('Connection', backref=db.backref('user', lazy='joined'), cascade="all")

    def toJson(self):
        ''' Represent the user as a JSON object. This is used to initialize the AngularJS APP as well
        as being available via AJAX to get updates to user information. '''
        return json.dumps({'email': self.email, 'first_name': self.first_name, 'last_name': self.last_name})

class Connection(db.Model):
    ''' Connection table for Oauth, via Flask-Social'''
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    provider_id = db.Column(db.String(255))
    provider_user_id = db.Column(db.String(255))
    access_token = db.Column(db.String(255))
    secret = db.Column(db.String(255))
    full_name = db.Column(db.String(255))
    display_name = db.Column(db.String(255))
    profile_url = db.Column(db.String(512))
    image_url = db.Column(db.String(512))
    rank = db.Column(db.Integer)
    
    __tablename__ = "connections"

    # TODO: this was an attempt to solve issue with multiple oauths. check git issue for flask-social
    __table_args__ = (db.UniqueConstraint('provider_id', 'provider_user_id', name='_providerid_userid_uc'), {})

application/forms.py
# Import custom forms from all of our modules
from .users.forms import *

# TODO: import any custom forms here

application/users/forms.py
# If your module needs custom forms, you can place them all in one spot here

application/users/views.py
import json 

from flask import render_template, redirect, request, current_app, session, flash, url_for, Blueprint, jsonify
from flask.ext.login import current_user
from flask.ext.security import LoginForm, RegisterForm, current_user, login_required, login_user, auth_token_required
from flask.ext.security.views import logout
from flask.ext.social.utils import get_provider_or_404
from flask.ext.social.views import connect_handler
from application.core import app


usersBlueprint = Blueprint('users', __name__, template_folder='templates/users')


@usersBlueprint.route('/user_details',  methods=['GET'])
@login_required
def user_details():
    return current_user.toJson()


@usersBlueprint.route('/profile')
@login_required
def profile():
    return render_template('security/profile.html', content='Profile Page', twitter_conn=app.social.twitter.get_connection())


@usersBlueprint.route('/profile/<provider_id>/post', methods=['POST'])
@login_required
def social_post(provider_id):
    message = request.form.get('message', None)

    if message:
        provider = get_provider_or_404(provider_id)
        api = provider.get_api()

        if provider_id == 'twitter':
            display_name = 'Twitter'
            api.PostUpdate(message)
        if provider_id == 'facebook':
            display_name = 'Facebook'
            api.put_object("me", "feed", message=message)

        flash('Message posted to %s: %s' % (display_name, message), 'info')

    return redirect(url_for('users.profile'))


@usersBlueprint.route('/register', methods=['GET', 'POST'])
@usersBlueprint.route('/register/<provider_id>', methods=['GET', 'POST'])
def register(provider_id=None):

    if current_user.is_authenticated():
        return redirect(request.referrer or current_app.config['SECURITY_POST_LOGIN_VIEW'])

    form = RegisterForm()

    if provider_id:
        provider = get_provider_or_404(provider_id)
        connection_values = session.get('failed_login_connection', None)
    else:
        provider = None
        connection_values = None

    if form.validate_on_submit():
        ds = current_app.security.datastore
        user = ds.create_user(email=form.email.data, password=form.password.data)
        ds.commit()

        # See if there was an attempted social login prior to registering
        # and if so use the provider connect_handler to save a connection
        connection_values = session.pop('failed_login_connection', None)

        if connection_values:
            connection_values['user_id'] = user.id
            connect_handler(connection_values, provider)

        if login_user(user):
            ds.commit()
            flash('Account created successfully', 'info')
            return redirect(url_for('security.profile'))

        return render_template('security/thanks.html', user=user)

    login_failed = int(request.args.get('login_failed', 0))
    return render_template('security/register_user.html', register_user_form=form, provider=provider, login_failed=login_failed, connection_values=connection_values)

application/views.py
import os

from flask import request, session, current_app, render_template, Blueprint, jsonify, abort, make_response
from flask_wtf.csrf import generate_csrf, validate_csrf
from flask.ext.login import current_user
from flask.ext.security import LoginForm

from models import User


mainBlueprint = Blueprint('main', __name__, template_folder="static")


@mainBlueprint.route('/', methods=['GET'])
def index():
    # Get user object ti put in the initial 'seed' portion of the AngularJS app
    if 'user_id' in session:
        user = User.query.get(session['user_id'])
    else:
        user = None
    
    # TODO: deal with this after CSRF issue handled
    # Give the AngularJS app an initial CSRF token (which can be regenerated later)
    #csrf = generate_csrf()
    #csrf = LoginForm().csrf_token.current_token

    # Give the AngularJS app an initial boolean if the user is logged in via session cookie
    loggedIn = current_user.is_authenticated()

    return render_template('index.html', user=user, loggedIn=loggedIn)
    
# TODO: deal with this after CSRF issue handled
# @mainBlueprint.route('csrf', methods=['GET'])
# def csrf():
#     return jsonify({"csrf": LoginForm().csrf_token.current_token})

application/templates/base.html
<html>
    <head>
        <title>{% block title %}My New Boilerplate Site{% endblock %}</title>

        {% block css %}
        <!-- Bootstrap and bootstrap-theme -->
        <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.1.1/css/bootstrap.min.css" />
        <!-- <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.1.1/css/bootstrap-theme.min.css" /> -->

        <!-- FontAwesome -->
        <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/font-awesome/4.0.3/css/font-awesome.min.css" />
        {% endblock %}

        {% block script %}
        <!-- jQuery -->
        <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.0/jquery.min.js" type="text/javascript"></script>

        <!-- Bootstrap JS -->
        <script src="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.1.1/js/bootstrap.js" type="text/javascript"></script>
        {% endblock %}
    </head>

    <body>
        <div id="header">{% block header %}{% endblock %}</div>
        <div id="messages-wrap">
            <div id="messages">
                {% for category, msg in get_flashed_messages(with_categories=true) %}
                <p class="message flash-{{ category }}">{{ msg }}</p>
                {% endfor %}
            </div>
        </div>
        <div id="content">{% block content %}{% endblock %}</div>
        <div id="footer">{% block footer %}{% endblock %}</div>
    </body>
</html>

application/templates/index.html
<h1>w00t, this all works!</h1>

application/templates/macros.html
  {% macro render_field(field) %}
      <div class="form_field">
      {{ field.label(class="label") }}
      {% if field.errors %}
          {% set css_class = 'has_error ' + kwargs.pop('class', '') %}
          {{ field(class=css_class, **kwargs) }}
          <ul class="errors">{% for error in field.errors %}<li>{{ error|e }}</li>{% endfor %}</ul>
      {% else %}
          {{ field(**kwargs) }}
      {% endif %}
      </div>
  {% endmacro %}

application/templates/users/login_user.html
{% from "users/macros.html" import social_login %}
{% from 'macros.html' import render_field %}

{% extends "base.html" %}

{% block content %}
<div class="page-header">
  <h1>Log In</h1>
</div>
<div class="row content">
  <div class="span4 offset1">
    <form class="well" action="{{ url_for('security.login') }}" method="POST">
      {{ form.hidden_tag() }}
      {{ render_field(form.email) }}
      {{ render_field(form.password) }}
      <label class="checkbox">{{ form.remember()|safe }} Remember me</label>
      <button type="submit" class="btn btn-primary btn-large">Login</button>
    </form>
  </div>
  <div class="span2 col2">
    <h3>OR</h3>
  </div>
  <div class="span4 col3">
    {{ social_login('twitter', 'Twitter' )}}
    {{ social_login('facebook', 'Facebook' )}}
    <!-- {{ social_login('github', 'GitHub' )}} -->
  </div>
</div>
{% endblock %}

application/templates/users/macros.html
{% macro social_login(provider_id, display_name) %}
  <form action="{{ url_for('social.login', provider_id=provider_id) }}" method="POST">
    <button type="submit" class="btn btn-primary btn-large">Login with {{ display_name }}</button>
  </form>
{% endmacro %}

{% macro show_provider_button(provider_id, display_name, conn, show_update_form=True) %}
  <div class="span6">
    <h2>{{ display_name }}</h2>
    <hr />
    {% if conn %}
      {% if show_update_form %}
        <form action="{{ url_for('users.social_post', provider_id=provider_id) }}" method="POST" class="post-update">
          <fieldset>
            <div class="control-group">
              <textarea class="input-xlarge" name="message" rows="3">Hello from Flask-Social-Example!</textarea>
            </div>
            <button type="submit" class="btn btn-primary btn-large"><i class="icon-share icon-white"></i> Post Update</button>
          </fieldset>
        </form>
      {% endif %}
      <form action="{{ url_for('social.remove_connection', provider_id=conn.provider_id, provider_user_id=conn.provider_user_id) }}?__METHOD_OVERRIDE__=DELETE" method="POST" class="remove-connection">
        <button type="submit" class="btn btn-danger"><i class="icon-trash icon-white"></i> Remove {{ display_name }} Connection</button>
      </form>
    {% else %}
      <form action="{{ url_for('social.connect', provider_id=provider_id) }}" method="POST" class="create-connection">
        <fieldset>
          <div class="control-group">
            <button type="submit" class="btn btn-success btn-large"><i class="icon-share icon-white"></i> Connect with {{ display_name }}</button>
          </div>
        </fieldset>
      </form>
    {% endif %}
  </div>
{% endmacro %}

{% macro social_register(provider_id, display_name) %}
  <form action="{{ url_for('social.login', provider_id=provider_id) }}" method="POST">
    <button type="submit" class="btn btn-primary btn-large">Register with {{ display_name }}</button>
  </form>
{% endmacro %}

application/templates/users/profile.html
{% from "users/macros.html" import show_provider_button %}
{% extends "base.html" %}

{% block content %}
<div class="page-header">
  <h1>Hello, {{ current_user.email }}!</h1>
</div>
<div class="row">
  {{ show_provider_button('twitter', 'Twitter', twitter_conn) }}
  {{ show_provider_button('facebook', 'Facebook', facebook_conn) }}
</div>
<!--
<div class="row" style="margin-top:50px;">
{{ show_provider_button('github', 'GitHub', github_conn, False)}}
</div>
-->
{% endblock %}

application/templates/users/register.html
{% from "users/macros.html" import social_register %}
{% from "macros.html" import render_field %}

{% extends "base.html" %}

{% block content %}
<div class="page-header">
  <h1>Register</h1>
</div>
{% if login_failed %}
<h3>Register with your {{ provider.name }} account: {{ connection_values['display_name'] }}</h3>
{% endif %}
<div class="row content">
  <div class="span4 offset1">
    <form class="well" action="{{ url_for('users.register', provider_id=provider.id if provider else None) }}" method="POST">
      {{ form.hidden_tag() }}
      {{ render_field(form.email) }}
      {{ render_field(form.password) }}
      <button type="submit" class="btn btn-primary btn-large">Register</button>
    </form>
  </div>
  {% if not login_failed %}
  <div class="span2 col2">
    <h3>OR</h3>
  </div>
  <div class="span4 col3">
    {{ social_register('twitter', 'Twitter' )}}
    {{ social_register('facebook', 'Facebook' )}}
    <!-- {{ social_register('github', 'GitHub' )}} -->
  </div>
  {% endif %}
</div>
{% endblock %}

application/templates/users/thanks.html
{% block content %}
<h2>Thank You!</h2>

<p>Thanks for registering <strong>{{ user.email }}</strong>! You can now view your <a href="{{ url_for('users.profile') }}">profile page</a></p>
{% endblock %}